### ISSUE TITLE
JS for Expand All/Close All

### ISSUE THREAD

**Issue by dev-bhatia** [dev-bhatia/public_html#1]
- Allow Expand/Close for each section
- Allow Expand All/Close All for all sections
- Include icons indicating these actions

**Comment by r-jo** [comment]
Can you expand on what you mean by expand and close all sections? Are you talking about modals? And what is included in "all sections"?

**Comment by r-jo** [comment]
Check the develop branch :) . Let me know what you think.

**Comment by dev-bhatia** [comment]
Great work Raj! JS works as expected. Don't think I want to have an expand all/close all feature, but let me know if you think that would be nice to have.
